### ISSUE TITLE
incomplete project?

### ISSUE THREAD

**Issue by appengine8848** [FX31337/ex4_to_mq4_cli#1]
hello kenorb 

this seems incomplete, right?

**Comment by kenorb** [comment]
I believe it should work, but it was only tested on the demo version (`ex4_to_mq4_demo.exe`, filename hardcoded in the source code), so you need to have the full version to be able to test it (`ex4_to_mq4.exe` binary). I haven't be able to test it on the full version, as I couldn't find the right one, as the author stopped selling it.

This is just the wrapper to fake the execution of `ex4_to_mq4` and passing the files from the CLI, then faking GUI drag&dropping.

Since the original EXE binary got a lot of anti-cracking mechanisms in place, it may or may not work. There is a chance, it needs more testing and further work.

If you're able to handle complexity of the project, suggestions and pull requests are welcomed.

**Comment by appengine8848** [comment]
Could you leave your email and I send the compiled binary to you ?

I haven't check the code ,just compiled it successfully but when I run it report "unable to run demo.exe"

**Comment by appengine8848** [comment]
and someone send me a pic yesterday to show his program have a drap file window

**Comment by kenorb** [comment]
Try changing `EXE_NAME` value in `ex4_to_mq4_auto.c` to correct filename that you've.

**Comment by kenorb** [comment]
To summarize, this project is the wrapper for the existing EX4-TO-MQ4 Decompiler.

You can download the demo from the old version of: [http://purebeam.biz/#decompiler](https://web.archive.org/web/20120617184850/http://purebeam.biz:80/#decompiler). Filename: `ex4_to_mq4_demo.exe` and try this project on the demo. The file was here: https://purebeam.biz/files/ex4_to_mq4_demo.exe (it has been removed).

This project is just a wrapper and it's only compatible with Purebeam's version of EX4-TO-MQ4 Decompiler. But **it doesn't comes with the decompiler it-self**.

**Comment by motorheadtech** [comment]
I have the full version of ex4_to_mq4.exe how can i use this code to decomplie a protected ex4 file?

**Comment by kenorb** [comment]
> I have the full version of ex4_to_mq4.exe how can i use this code to decompile a protected ex4 file?

You compile the project to `ex4_to_mq4_auto.exe` file, place `ex4_to_mq4.exe` in the same folder, and run `ex4_to_mq4_auto.exe` as a wrapper, specifying in the argument what files you'd like to decompile. After run, it will execute `ex4_to_mq4.exe` by faking drag & drop operation of the files.

**Comment by eliteguru1226** [comment]
@kenorb 
Is there anyway to get mql4 from ex4 which was built for MT4 600++?
I believe that you've great experience in this field, so have solution.
Thank you in advance.

**Comment by kenorb** [comment]
> Is there anyway to get mql4 from ex4 which was built for MT4 600++?

I don't know any program that allows that.
